In [1]:
import numpy as np
import pandas as pd

In [2]:
df_canada = pd.read_excel("immigration_to_canada.xlsx",
                      sheet_name="Canada by Citizenship",
                      skiprows=range(20),
                      skipfooter=2)

In [ ]:
df_canada.head() # display first 5 heads

In [ ]:
df_canada.columns

In [3]:
df_canada.drop(['AREA','REG','DEV','Type','Coverage'], axis=1, inplace=True)
df_canada.columns

Index([  'OdName', 'AreaName',  'RegName',  'DevName',       1980,       1981,
             1982,       1983,       1984,       1985,       1986,       1987,
             1988,       1989,       1990,       1991,       1992,       1993,
             1994,       1995,       1996,       1997,       1998,       1999,
             2000,       2001,       2002,       2003,       2004,       2005,
             2006,       2007,       2008,       2009,       2010,       2011,
             2012,       2013],
      dtype='object')

In [4]:
df_canada.rename(columns={'OdName':'Country', 'AreaName':'Continent', 'RegName':'Region'}, inplace=True)
df_canada.columns

Index([  'Country', 'Continent',    'Region',   'DevName',        1980,
              1981,        1982,        1983,        1984,        1985,
              1986,        1987,        1988,        1989,        1990,
              1991,        1992,        1993,        1994,        1995,
              1996,        1997,        1998,        1999,        2000,
              2001,        2002,        2003,        2004,        2005,
              2006,        2007,        2008,        2009,        2010,
              2011,        2012,        2013],
      dtype='object')

In [5]:
df_canada['Total'] = df_canada.sum(axis=1)

In [6]:
df_canada.isnull().sum()

Country      0
Continent    0
Region       0
DevName      0
1980         0
1981         0
1982         0
1983         0
1984         0
1985         0
1986         0
1987         0
1988         0
1989         0
1990         0
1991         0
1992         0
1993         0
1994         0
1995         0
1996         0
1997         0
1998         0
1999         0
2000         0
2001         0
2002         0
2003         0
2004         0
2005         0
2006         0
2007         0
2008         0
2009         0
2010         0
2011         0
2012         0
2013         0
Total        0
dtype: int64

In [7]:
df_canada.describe()

,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2005,2006,2007,2008,2009,2010,2011,2012,2013,Total
count,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,...,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000
mean,508.394872,566.989744,534.723077,387.435897,376.497436,358.861538,441.271795,691.133333,714.389744,843.241026,...,1320.292308,1266.958974,1191.820513,1246.394872,1275.733333,1420.287179,1262.533333,1313.958974,1320.702564,32867.451282
std,1949.588546,2152.643752,1866.997511,1204.333597,1198.246371,1079.309600,1225.576630,2109.205607,2443.606788,2555.048874,...,4425.957828,3926.717747,3443.542409,3694.573544,3829.630424,4462.946328,4030.084313,4247.555161,4237.951988,91785.498686
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.500000,0.500000,1.000000,1.000000,...,28.500000,25.000000,31.000000,31.000000,36.000000,40.500000,37.500000,42.500000,45.000000,952.000000
50%,13.000000,10.000000,11.000000,12.000000,13.000000,17.000000,18.000000,26.000000,34.000000,44.000000,...,210.000000,218.000000,198.000000,205.000000,214.000000,211.000000,179.000000,233.000000,213.000000,5018.000000
75%,251.500000,295.500000,275.000000,173.000000,181.000000,197.000000,254.000000,434.000000,409.000000,508.500000,...,832.000000,842.000000,899.000000,934.500000,888.000000,932.000000,772.000000,783.000000,796.000000,22239.500000
max,22045.000000,24796.000000,20620.000000,10015.000000,10170.000000,9564.000000,9470.000000,21337.000000,27359.000000,23795.000000,...,42584.000000,33848.000000,28742.000000,30037.000000,29622.000000,38617.000000,36765.000000,34315.000000,34129.000000,691904.000000

In [8]:
df_canada.head()

,Country,Continent,Region,DevName,1980,1981,1982,1983,1984,1985,...,2005,2006,2007,2008,2009,2010,2011,2012,2013,Total
0,Afghanistan,Asia,Southern Asia,Developing regions,16,39,39,47,71,340,...,3436,3009,2652,2111,1746,1758,2203,2635,2004,58639
1,Albania,Europe,Southern Europe,Developed regions,1,0,0,0,0,0,...,1223,856,702,560,716,561,539,620,603,15699
2,Algeria,Africa,Northern Africa,Developing regions,80,67,71,69,63,44,...,3626,4807,3623,4005,5393,4752,4325,3774,4331,69439
3,American Samoa,Oceania,Polynesia,Developing regions,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,6
4,Andorra,Europe,Southern Europe,Developed regions,0,0,0,0,0,0,...,0,1,1,0,0,0,0,1,1,15

In [39]:
import matplotlib as mpl
import matplotlib.pyplot as plt

In [25]:
years = list(map(str, range(1980, 2014)))

In [26]:
print(years)

['1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013']

In [15]:
df_canada.set_index('Country', inplace=True)

In [9]:
df_canada.Country

0         Afghanistan
1             Albania
2             Algeria
3      American Samoa
4             Andorra
            ...
190          Viet Nam
191    Western Sahara
192             Yemen
193            Zambia
194          Zimbabwe
Name: Country, Length: 195, dtype: object

In [10]:
df_canada[['Country', 1980]]

            Country  1980
0       Afghanistan    16
1           Albania     1
2           Algeria    80
3    American Samoa     0
4           Andorra     0
..              ...   ...
190        Viet Nam  1191
191  Western Sahara     0
192           Yemen     1
193          Zambia    11
194        Zimbabwe    72

[195 rows x 2 columns]

In [14]:
df_canada.iloc[1, 2]

'Southern Europe'

In [18]:
# 1. the full row data (all columns)
print(df_canada.loc['Japan'])

# alternate methods
print(df_canada.iloc[87])
print(df_canada[df_canada.index == 'Japan'].T.squeeze())

Continent                 Asia
Region            Eastern Asia
DevName      Developed regions
1980                       701
1981                       756
1982                       598
1983                       309
1984                       246
1985                       198
1986                       248
1987                       422
1988                       324
1989                       494
1990                       379
1991                       506
1992                       605
1993                       907
1994                       956
1995                       826
1996                       994
1997                       924
1998                       897
1999                      1083
2000                      1010
2001                      1092
2002                       806
2003                       817
2004                       973
2005                      1067
2006                      1212
2007                      1250
2008                      1284
2009                      1194
2010                      1168
2011                      1265
2012                      1214
2013                       982
Total                    27707
Name: Japan, dtype: object
Continent                 Asia
Region            Eastern Asia
DevName      Developed regions
1980                       701
1981                       756
1982                       598
1983                       309
1984                       246
1985                       198
1986                       248
1987                       422
1988                       324
1989                       494
1990                       379
1991                       506
1992                       605
1993                       907
1994                       956
1995                       826
1996                       994
1997                       924
1998                       897
1999                      1083
2000                      1010
2001                      1092
2002                       806
2003                       817
2004                       973
2005                      1067
2006                      1212
2007                      1250
2008                      1284
2009                      1194
2010                      1168
2011                      1265
2012                      1214
2013                       982
Total                    27707
Name: Japan, dtype: object
Continent                 Asia
Region            Eastern Asia
DevName      Developed regions
1980                       701
1981                       756
1982                       598
1983                       309
1984                       246
1985                       198
1986                       248
1987                       422
1988                       324
1989                       494
1990                       379
1991                       506
1992                       605
1993                       907
1994                       956
1995                       826
1996                       994
1997                       924
1998                       897
1999                      1083
2000                      1010
2001                      1092
2002                       806
2003                       817
2004                       973
2005                      1067
2006                      1212
2007                      1250
2008                      1284
2009                      1194
2010                      1168
2011                      1265
2012                      1214
2013                       982
Total                    27707
Name: Japan, dtype: object

In [19]:
# 2. for year 2013
print(df_canada.loc['Japan', 2013])

# alternate method
print(df_canada.iloc[87, 36]) # year 2013 is the last column, with a positional index of 36

982
982

In [20]:
# 3. for years 1980 to 1985
print(df_canada.loc['Japan', [1980, 1981, 1982, 1983, 1984, 1984]])
print(df_canada.iloc[87, [3, 4, 5, 6, 7, 8]])

1980    701
1981    756
1982    598
1983    309
1984    246
1984    246
Name: Japan, dtype: object
1980    701
1981    756
1982    598
1983    309
1984    246
1985    198
Name: Japan, dtype: object

In [21]:
df_canada.columns = list(map(str, df_canada.columns))

In [22]:
# 1. create the condition boolean series
condition = df_canada['Continent'] == 'Asia'
print(condition)

Country
Afghanistan        True
Albania           False
Algeria           False
American Samoa    False
Andorra           False
                  ...
Viet Nam           True
Western Sahara    False
Yemen              True
Zambia            False
Zimbabwe          False
Name: Continent, Length: 195, dtype: bool

In [23]:
# 2. pass this condition into the dataFrame
df_canada[condition]

,Continent,Region,DevName,1980,1981,1982,1983,1984,1985,1986,...,2005,2006,2007,2008,2009,2010,2011,2012,2013,Total
Country,,,,,,,,,,,,,,,,,,,,,
Afghanistan,Asia,Southern Asia,Developing regions,16,39,39,47,71,340,496,...,3436,3009,2652,2111,1746,1758,2203,2635,2004,58639
Armenia,Asia,Western Asia,Developing regions,0,0,0,0,0,0,0,...,224,218,198,205,267,252,236,258,207,3310
Azerbaijan,Asia,Western Asia,Developing regions,0,0,0,0,0,0,0,...,359,236,203,125,165,209,138,161,57,2649
Bahrain,Asia,Western Asia,Developing regions,0,2,1,1,1,3,0,...,12,12,22,9,35,28,21,39,32,475
Bangladesh,Asia,Southern Asia,Developing regions,83,84,86,81,98,92,486,...,4171,4014,2897,2939,2104,4721,2694,2640,3789,65568
Bhutan,Asia,Southern Asia,Developing regions,0,0,0,0,1,0,0,...,5,10,7,36,865,1464,1879,1075,487,5876
Brunei Darussalam,Asia,South-Eastern Asia,Developing regions,79,6,8,2,2,4,12,...,4,5,11,10,5,12,6,3,6,600
Cambodia,Asia,South-Eastern Asia,Developing regions,12,19,26,33,10,7,8,...,370,529,460,354,203,200,196,233,288,6538
China,Asia,Eastern Asia,Developing regions,5123,6682,3308,1863,1527,1816,1960,...,42584,33518,27642,30037,29622,30391,28502,33024,34129,659962
"China, Hong Kong Special Administrative Region",Asia,Eastern Asia,Developing regions,0,0,0,0,0,0,0,...,729,712,674,897,657,623,591,728,774,9327
"China, Macao Special Administrative Region",Asia,Eastern Asia,Developing regions,0,0,0,0,0,0,0,...,21,32,16,12,21,21,13,33,29,284
Cyprus,Asia,Western Asia,Developing regions,132,128,84,46,46,43,48,...,7,9,4,7,6,18,6,12,16,1126
Democratic People's Republic of Korea,Asia,Eastern Asia,Developing regions,1,1,3,1,4,3,0,...,14,10,7,19,11,45,97,66,17,388
Georgia,Asia,Western Asia,Developing regions,0,0,0,0,0,0,0,...,114,125,132,112,128,126,139,147,125,2068
India,Asia,Southern Asia,Developing regions,8880,8670,8147,7338,5704,4211,7150,...,36210,33848,28742,28261,29456,34235,27509,30933,33087,691904
Indonesia,Asia,South-Eastern Asia,Developing regions,186,178,252,115,123,100,127,...,632,613,657,661,504,712,390,395,387,13150
Iran (Islamic Republic of),Asia,Southern Asia,Developing regions,1172,1429,1822,1592,1977,1648,1794,...,5837,7480,6974,6475,6580,7477,7479,7534,11291,175923
Iraq,Asia,Western Asia,Developing regions,262,245,260,380,428,231,265,...,2226,1788,2406,3543,5450,5941,6196,4041,4918,69789
Israel,Asia,Western Asia,Developing regions,1403,1711,1334,541,446,680,1212,...,2446,2625,2401,2562,2316,2755,1970,2134,1945,66508
Japan,Asia,Eastern Asia,Developed regions,701,756,598,309,246,198,248,...,1067,1212,1250,1284,1194,1168,1265,1214,982,27707
Jordan,Asia,Western Asia,Developing regions,177,160,155,113,102,179,181,...,1940,1827,1421,1581,1235,1831,1635,1206,1255,35406
Kazakhstan,Asia,Central Asia,Developing regions,0,0,0,0,0,0,0,...,506,408,436,394,431,377,381,462,348,8490
Kuwait,Asia,Western Asia,Developing regions,1,0,8,2,1,4,4,...,66,35,62,53,68,67,58,73,48,2025
Kyrgyzstan,Asia,Central Asia,Developing regions,0,0,0,0,0,0,0,...,173,161,135,168,173,157,159,278,123,2353
Lao People's Democratic Republic,Asia,South-Eastern Asia,Developing regions,11,6,16,16,7,17,21,...,42,74,53,32,39,54,22,25,15,1089
Lebanon,Asia,Western Asia,Developing regions,1409,1119,1159,789,1253,1683,2576,...,3709,3802,3467,3566,3077,3432,3072,1614,2172,115359
Malaysia,Asia,South-Eastern Asia,Developing regions,786,816,813,448,384,374,425,...,593,580,600,658,640,802,409,358,204,24417
Maldives,Asia,Southern Asia,Developing regions,0,0,0,1,0,0,0,...,0,0,2,1,7,4,3,1,1,30
Mongolia,Asia,Eastern Asia,Developing regions,0,0,0,0,0,0,0,...,59,64,82,59,118,169,103,68,99,952
Myanmar,Asia,South-Eastern Asia,Developing regions,80,62,46,31,41,23,18,...,210,953,1887,975,1153,556,368,193,262,9245
Nepal,Asia,Southern Asia,Developing regions,1,1,6,1,2,4,13,...,607,540,511,581,561,1392,1129,1185,1308,10222
Oman,Asia,Western Asia,Developing regions,0,0,0,8,0,0,0,...,14,18,16,10,7,14,10,13,11,224
Pakistan,Asia,Southern Asia,Developing regions,978,972,1201,900,668,514,691,...,14314,13127,10124,8994,7217,6811,7468,11227,12603,241600
Philippines,Asia,South-Eastern Asia,Developing regions,6051,5921,5249,4562,3801,3150,4166,...,18139,18400,19837,24887,28573,38617,36765,34315,29544,511391
Qatar,Asia,Western Asia,Developing regions,0,0,0,0,0,0,1,...,11,2,5,9,6,18,3,14,6,157
Republic of Korea,Asia,Eastern Asia,Developing regions,1011,1456,1572,1081,847,962,1208,...,5832,6215,5920,7294,5874,5537,4588,5316,4509,142581
Saudi Arabia,Asia,Western Asia,Developing regions,0,0,1,4,1,2,5,...,198,252,188,249,246,330,278,286,267,3425
Singapore,Asia,South-Eastern Asia,Developing regions,241,301,337,169,128,139,205,...,392,298,690,734,366,805,219,146,141,14579
Sri Lanka,Asia,Southern Asia,Developing regions,185,371,290,197,1086,845,1838,...,4930,4714,4123,4756,4547,4422,3309,3338,2394,148358
State of Palestine,Asia,Western Asia,Developing regions,0,0,0,0,0,0,0,...,453,627,441,481,400,654,555,533,462,6512
Syrian Arab Republic,Asia,Western Asia,Developing regions,315,419,409,269,264,385,493,...,1458,1145,1056,919,917,1039,1005,650,1009,31485
Tajikistan,Asia,Central Asia,Developing regions,0,0,0,0,0,0,0,...,85,46,44,15,50,52,47,34,39,503
Thailand,Asia,South-Eastern Asia,Developing regions,56,53,113,65,82,66,78,...,575,500,487,519,512,499,396,296,400,9174
Turkey,Asia,Western Asia,Developing regions,481,874,706,280,338,202,257,...,2065,1638,1463,1122,1238,1492,1257,1068,729,31781
Turkmenistan,Asia,Central Asia,Developing regions,0,0,0,0,0,0,0,...,40,26,37,13,20,30,20,20,14,310
United Arab Emirates,Asia,Western Asia,Developing regions,0,2,2,1,2,0,5,...,31,42,37,33,37,86,60,54,46,836
Uzbekistan,Asia,Central Asia,Developing regions,0,0,0,0,0,0,0,...,330,262,284,215,288,289,162,235,167,3368
Viet Nam,Asia,South-Eastern Asia,Developing regions,1191,1829,2162,3404,7583,5907,2741,...,1852,3153,2574,1784,2171,1942,1723,1731,2112,97146
Yemen,Asia,Western Asia,Developing regions,1,2,1,6,0,18,7,...,161,140,122,133,128,211,160,174,217,2985

In [30]:
haiti = df_canada.loc['Haiti', years]
haiti.head()

1980    1666
1981    3692
1982    3498
1983    2860
1984    1418
Name: Haiti, dtype: object

In [34]:
haiti.index = haiti.index.map(int)

In [37]:
haiti.plot(kind='line')

In [36]:
%matplotlib notebook

In [40]:
plt.title('Immigration from Haiti')
plt.xlabel('Years')
plt.ylabel('Number of immigrants')

Text(36.902777777777786, 0.5, 'Number of immigrants')

In [43]:
plt.text(2000, 60000, '2010 Earthquake')
plt.show()